Feature/support last day of month (#1)
harrisiirak/cron-parser pull request #183
Opened 2020-05-18 22:51 UTC by heitara

* extent the cron-parse to support L symbol in dayOfMonth section.
* extend tests and sort the list of daysOfMonth

2020-05-18 23:05 UTC, heitara commented
For full specification check the following page https://www.netiq.com/documentation/cloud-manager-2-5/ncm-reference/data/bexyssf.html

2020-06-15 10:51 UTC, mete89 commented
@harrisiirak ?

2020-06-15 11:23 UTC, harrisiirak commented on lib/date.js
> +  return this._date.month() != newDate.month();
```suggestion
  return this._date.month() !== newDate.month();
```

2020-06-15 11:27 UTC, harrisiirak commented on lib/expression.js
> +        if(field === "dayOfMonth" && result === "L") {
```suggestion
        if(field === 'dayOfMonth' && result === 'L') {
```
No linting rules that enforce single-quotes here but they are definitely preferred.

2020-06-15 11:30 UTC, harrisiirak commented on lib/expression.js
>      return +val;
```suggestion
    return field === 'dayOfMonth' && result === 'L' ? val : +val;
```

2020-06-15 11:33 UTC, harrisiirak commented on lib/expression.js
> +        if(dayOfMonth === "L") {
```suggestion
        if(dayOfMonth === 'L') {
```

2020-06-15 11:38 UTC, harrisiirak commented on test/parser_day_of_month.js
> +      // console.log(next.toString());
```suggestion
```

2020-06-15 11:42 UTC, harrisiirak commented on test/parser_day_of_month.js
> +      // console.log(next.toString());
```suggestion
```

2020-06-15 11:43 UTC, harrisiirak commented on test/parser_day_of_month.js
> +var util = require('util');
It's also recommended to actually validate the results that `interval.next()` returns, otherwise we don't have any verified proof that iteration is returning correct dates.

2020-06-15 11:44 UTC, harrisiirak commented on lib/expression.js
> +      mappedFields.dayOfMonth.sort((a,b) => {
Ideally, this code should be located in `CronExpression._parseField`.

2020-06-15 11:57 UTC, harrisiirak commented on lib/expression.js
> +    if(this._fields.dayOfMonth.length > 0 && this._fields.dayOfMonth.indexOf("L") >= 0) {
Maybe we can also separate this into a separate helper function? Currently, it feels a bit ad-hoc.

2020-09-19 13:26 UTC, harrisiirak commented
@heitara have you had the time to go through my feedback to your PR?

2020-09-19 17:43 UTC, heitara commented on test/parser_day_of_month.js
> +var util = require('util');
@harrisiirak what do you mean by validate? Is there such a helper function or you want a new test that covers it?

2020-09-19 17:44 UTC, heitara commented on lib/expression.js
> +      mappedFields.dayOfMonth.sort((a,b) => {
I don't think this can be moved there easily without the needed refactoring. You can add a TODO note if it's really important to be done in the future.

2020-10-12 19:04 UTC, shubhamms commented
@heitara @harrisiirak do you guys have an ETA for this change? I was hoping to use this feature in one of my projects :)

2020-10-12 19:20 UTC, harrisiirak commented
@shubhamms I just noticed (no re-request) that there have been some changes, I'll have another look later in this week.

2020-10-26 22:00 UTC, shubhamms commented
@harrisiirak any updates?

2020-10-26 22:49 UTC, harrisiirak requested changes
@heitara thanks for your work and updates!

I added some comments but it looks good. Let me know if you have any additional question.

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +CronExpression.dayValidCharactersDayOfMonth = /^[\d|L|/|*|\-|,|\?]+$/;
```suggestion
CronExpression.dayOfMonthValidCharacters = /^[\d|L|/|*|\-|,|\?]+$/;
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +  dayOfMonth: CronExpression.dayValidCharactersDayOfMonth,
```suggestion
  dayOfMonth: CronExpression.dayOfMonthValidCharacters,
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
>  CronExpression.dayValidCharacters = /^[\d|/|*|\-|,|\?]+$/;
```suggestion
CronExpression.dayOfWeekValidCharacters = /^[\d|/|*|\-|,|\?]+$/;
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
>    dayOfWeek: CronExpression.dayValidCharacters,
```suggestion
  dayOfWeek: CronExpression.dayOfWeekValidCharacters,
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +        if(field === 'dayOfMonth' && result === 'L') {
```suggestion
        if (field === 'dayOfMonth' && result === 'L') {
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +          return a - b
```suggestion
          return a - b;
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +        let bIsNumber = typeof b === 'number';
```suggestion
        var aIsNumber = typeof a === 'number';
        var bIsNumber = typeof b === 'number';
```

Just for backwards compability.

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +      mappedFields.dayOfMonth.sort((a,b) => {
```suggestion
      mappedFields.dayOfMonth.sort(function(a,b) {
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
>          return dayOfMonth <= daysInMonth;
```suggestion
        return dayOfMonth === 'L' ? true : dayOfMonth <= daysInMonth;
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +    if(isLInDayOfMonth(this._fields.dayOfMonth)) {
```suggestion
    if (isLInDayOfMonth(this._fields.dayOfMonth)) {
```

2020-10-26 22:49 UTC, harrisiirak commented on lib/expression.js
> +    return field === 'dayOfMonth' && val === 'L'? val : +val;
I need to test this myself, but we could possibly generalise in this way:

```suggestion
    return isNan(+val) ? val : +val;
```

If this doesn't work, ignore my suggestion.

2020-10-26 22:50 UTC, harrisiirak commented
> @harrisiirak did you get a chance to look at the PR?

Thanks for reminding me about this! Gave a quick review.

2020-10-28 20:00 UTC, heitara commented
I've accepted the proposed improvements. What's next @harrisiirak ?

2020-10-29 08:50 UTC, harrisiirak commented
@heitara looks like tests are failing. The change I suggested [here](https://github.com/harrisiirak/cron-parser/pull/183#discussion_r512314362) seems to be creating some weird side-effects, however if I reverted this change locally, I'm still seeing some (3) failing test cases.

2020-11-02 18:35 UTC, rohailmalhi-nbs commented on lib/expression.js
> +    return field === 'dayOfMonth' && val === 'L'? val : +val;
isNan is generating a error . Saying isNan is not defined. Shouldnt it be **isNaN**

2020-11-02 18:49 UTC, rohailmalhi-nbs requested changes

2020-11-02 18:49 UTC, rohailmalhi-nbs commented on lib/expression.js
> +    return isNan(+val) ? val : +val;
@heitara @harrisiirak isNan should be replaced by isNaN. This is generating an error.

2020-11-04 14:14 UTC, heitara commented on lib/expression.js
> +    return isNan(+val) ? val : +val;
I agree.

2020-11-04 14:19 UTC, heitara commented
@harrisiirak could you please fix the failing tests in the repo. I saw them in the following commit 362a58d251386f61689156f1737a32f42041b5cc you can see the same failing there. I believe once those are resolved we can merge and close this PR if everything else is working.

2020-11-04 14:48 UTC, harrisiirak commented
@heitara 

> could you please fix the failing tests in the repo

Not sure what are proposing here (what I should be fixing?), and I can't (or I can?) directly push into your forked brach. 

> I saw them in the following commit 362a58d you can see the same failing there.

Tested this (reverted to non-strict comparison as before) locally and this doesn't seem to help. The same test cases are still failing, therefore the problem is somewhere else.

2020-11-04 15:02 UTC, heitara commented
what's the actual problem which we are chasing? I'm a bit confused? I was thinking the problem is in the tests?

2020-11-04 15:05 UTC, harrisiirak commented
@heitara 

<img width="1273" alt="Screenshot 2020-11-04 at 17 03 14" src="https://user-images.githubusercontent.com/185315/98127767-bd648380-1ebf-11eb-82a7-0575a93ce9d5.png">

I saw this in my local environment, but appears that there was something funky with my local branch state: re-synced your feature branch from the scratch and tests are now passing as expected. Sorry about the confusion!

2020-11-04 15:06 UTC, heitara commented
I see this - 
<img width="917" alt="Screenshot 2020-11-04 at 17 05 42" src="https://user-images.githubusercontent.com/1253070/98127995-04527900-1ec0-11eb-886f-d1cd90c5be02.png">

2020-11-04 15:07 UTC, harrisiirak approved these changes

2020-11-04 15:08 UTC, merged

2020-11-04 15:08 UTC, heitara commented
I'm seeing the same 3 tests failing on my local machine as well. I tracked them to be failing before my PR, that's why I asked you to check those. I'm not sure what is causing such odd behavior.

2020-11-04 15:24 UTC, harrisiirak commented
@heitara yep, I was wondering too. However, I merged this PR (thanks again for your patience!) in and master branch tests are passing locally. After Travis decides to pickup the jobs and they are passing, I'll make a release.

2020-11-04 15:29 UTC, heitara commented
Sweet! Just to remind you, we don't have enough tests covering the new piece of functionality. If you add some or if you give me an idea I can add a few.