fIX: if any empty charater around comma
harrisiirak/cron-parser pull request #197
Opened 2020-10-22 06:43 UTC by DevXiaolan

see :  [test/empty_around_comma.js](test/empty_around_comma.js)

2020-10-29 06:38 UTC, DevXiaolan commented
Hi ?

2020-10-29 09:04 UTC, harrisiirak commented
@DevXiaolan thanks for your contribution and pointing out this issue!

Ideally, as this pattern `* * * * ,` (or `* * * * ,2`) is actually invalid, we should be throwing an error instead. Converting invalid statement into wildcard (*) may be a little bit confusing, therefore throwing a validation error may be more meaningful here.

2020-10-30 02:32 UTC, DevXiaolan commented
> @DevXiaolan thanks for your contribution and pointing out this issue!
> 
> Ideally, as this pattern `* * * * ,` (or `* * * * ,2`) is actually invalid, we should be throwing an error instead. Converting invalid statement into wildcard (*) may be a little bit confusing, therefore throwing a validation error may be more meaningful here.

Maybe you are right, I'll follow your advice later

2020-11-16 02:01 UTC, DevXiaolan commented
keep waiting

2020-11-16 07:11 UTC, harrisiirak commented
@DevXiaolan thanks for the update! I'll give a look.

Please use "Request Review" then I actually know when things are ready to review:
<img width="313" alt="Screenshot 2020-11-16 at 09 10 01" src="https://user-images.githubusercontent.com/185315/99222584-8fe6d680-27eb-11eb-900b-9804d4d9e23f.png">

2020-11-17 15:44 UTC, harrisiirak requested changes
Found a better way how we can actually simplify this. Let me know what do you think about this.

2020-11-17 15:44 UTC, harrisiirak commented on lib/expression.js
>      if (atoms.length > 1) {
Actually, I was playing around with this validation and I found that we can use a little bit simpler approach here. Let me know what you're thinking about this.

```suggestion
    if (!atoms.every(function (atom) {
      return atom.length > 0;
    })) {
      throw new Error('Invalid list value format');
    }

    if (atoms.length > 1) {
```

2020-11-17 15:44 UTC, harrisiirak commented on lib/expression.js
> +        if(atoms[i]){
If this if/else can be remove if my suggestion makes sense.

2020-11-17 15:44 UTC, harrisiirak commented on lib/expression.js
> +    throw new Error('Invalid cron expression, value can not specified as comma');
The same about this code path if my suggestions seems to fit.

2020-11-18 02:30 UTC, DevXiaolan commented on lib/expression.js
>      if (atoms.length > 1) {
LGTM

2020-11-18 02:42 UTC, DevXiaolan commented on lib/expression.js
> +    throw new Error('Invalid cron expression, value can not specified as comma');
this line pre-check the input values before calling  parseSequence()

2020-11-18 08:22 UTC, harrisiirak commented on lib/expression.js
> +    throw new Error('Invalid cron expression, value can not specified as comma');
No need for that anymore as validation happens with atoms.every.

2020-11-19 07:31 UTC, harrisiirak requested changes

2020-11-19 07:31 UTC, harrisiirak commented on lib/expression.js
> +
Still not needed as this special error doesn't create much additional value. If we remove this, it still throws `Invalid list value format` as an error, therefore we have pretty simple validation model to catch both cases.

2020-11-19 07:45 UTC, DevXiaolan commented on lib/expression.js
> +
你说的也有道理，

2020-11-19 07:57 UTC, harrisiirak approved these changes
LGTM! Thanks! I'll merge it after Travis run completes.

2020-11-19 08:07 UTC, merged