Feature: add support for serializing a cron expression instance into a string
harrisiirak/cron-parser pull request #214
Opened 2021-02-23 23:04 UTC by regevbr

Fix #213 (and use suggestions from PR #210)

- Added ability to stringify an expression.
- Added unit tests with 100% coverage to the added code
- Improved typings tests and definitions
- Added cool new definition that require TS4.2 so had to split the typings files
- Fixed a potential bug that would cause a change on a frozen field
- removed redundant (and unused) callback parameter from the parse method

2021-02-24 01:20 UTC, regevbr commented
@harrisiirak can you please CR? I know this is a big PR but I think it brings a lot of good with it

2021-02-24 10:02 UTC, harrisiirak commented
@regevbr sure, I'll try to over this during the weekend.

2021-02-24 10:12 UTC, regevbr commented
Thanks @harrisiirak I will add some comments to explain the changes so it will clearer what I did all over the place :-)

2021-02-24 10:17 UTC, regevbr commented on index.d.ts
> +export * from './types'
Since I added typings that are not supported before TS 4.1, I added a [mechanism](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) to allow different definitions per version. There is some strange bug with that mechinsm and it took me a good couple of hours to solve (without understanding why). The solution was to move the d.ts files to the root dir. I still wanted to keep all the typings in one place so this file just re exports everything

2021-02-24 10:22 UTC, regevbr commented on lib/expression.js
> +    stack.sort(CronExpression._sortCompareFn);
Better to take the chars into account when sorting here

2021-02-24 10:24 UTC, regevbr commented on lib/expression.js
> +CronExpression._handleMaxDaysInMonth = function(mappedFields) {
Took existing code out for code resuse in the stringify logic

2021-02-24 10:26 UTC, regevbr commented on lib/expression.js
> +CronExpression._freezeFields = function(fields) {
I moved all the freeze ops to a single place so the responsibility will be on the constructor alone

2021-02-24 11:06 UTC, regevbr commented on lib/expression.js
> +CronExpression._sortCompareFn = function(a, b) {
since the fields can contain chars we need to sort them all the same way

2021-02-24 11:09 UTC, regevbr commented on lib/expression.js
> +CronExpression.parse = function parse(expression, options) {
callback is not really being used and never even being called

2021-02-24 11:09 UTC, regevbr commented on lib/expression.js
> +      mappedFields[key] = fields[i];
freeze will be handled by the constructor later

2021-02-24 11:10 UTC, regevbr commented on lib/expression.js
> +        var copy = [];
We don't want the caller to change the fields after the fact so we copy all of them

2021-02-24 11:11 UTC, regevbr commented on lib/expression.js
> +          .filter(function(item, pos, ary) {
remove duplicates

2021-02-24 11:12 UTC, regevbr commented on lib/parser.js
> +          result = CronParser._parseEntry('0 ' + entry);
not safe to use this here as someone might import the method on its own...

2021-02-24 11:13 UTC, regevbr commented on types/common.d.ts
> +export interface CronDate {
We don't really expose CronDate as a class and as such, it should be treated as an interface

2021-02-24 11:13 UTC, regevbr commented on types/common.d.ts
> +export interface ICronExpression<CronFields, IsIterable extends boolean> {
We don't really expose CronExpression as a class and as such, it should be treated as an interface

2021-02-24 11:13 UTC, regevbr commented on types/common.d.ts
> +export interface ICronExpression<CronFields, IsIterable extends boolean> {
CronFields can be simple or complicated (i.e. ts version 4.1 or above)

2021-02-28 13:19 UTC, harrisiirak requested changes
@regevbr thanks for your contribution! I'll try to give an another round of review later, but mostly it looks very good - added some minor comments/ideas/suggestions.

2021-02-28 13:19 UTC, harrisiirak commented on lib/parser.js
> +CronParser.stringifyExpression = function stringifyExpression (fields, options) {
Only argument against this name is that it doesn't take expression as an input. I'm thinking more like about `createExpressionFromFields`, however, this looks a bit clumsy. Maybe there is even a better alternative for these both.

2021-02-28 13:19 UTC, harrisiirak commented on lib/expression.js
> +      if (!value) { // Use default value
So basically, if I understand this logic correctly:

- When a field is present in `fields`, run the constraint validation and use provided field values if possible; if it's out of the range, throw an error
- When a field is not present it `fields`, fill its value with provided defaults

What I'm thinking is that maybe we can unify this behaviour somehow. I would prefer that both cases (an empty array and undefined) throws an error. However, if it makes sense to rather fill the field with defaults, let me know.

2021-02-28 13:24 UTC, regevbr commented on test/index-ts3.test-d.ts
> +expectType<readonly (number | 'L')[]>(interval.fields.dayOfMonth);
It is used in the actual type definition. In the assertion part, it is more resilient to use the actual type and not a type alias because changing the type alias will not cause the test to fail... Thoughts?

2021-02-28 13:25 UTC, regevbr commented on test/index-ts3.test-d.ts
> +expectType<void>(parseFile('path', (err: any, data: StringResult) => console.log(data)))
Tests don't really run the ts code. This is just a place holder to it will compile

2021-02-28 13:27 UTC, regevbr commented on types/index.d.ts
> +import {
I agree but this is why I took out most of what I could into the common part so it will be shared... In the future it will be easier to deprectae older ts by just removing the old definition file without trying to use all the new cool features at once. This way we can progress in 2 fields at once. I agree that it creates an overhead but as with everything in life, it is about balance. If you think the cons are heavier than the pros, I can revert to only using the old ts defentitions.

2021-02-28 13:29 UTC, regevbr commented on lib/expression.js
> +CronExpression.charConstraints = [
Actually it will be even more complicated once you add support for the other L char that can follow any integer haha. But sure I can look into it.

2021-02-28 13:30 UTC, regevbr commented on test/stringify.js
> +    var expected = '0 * * * * *';
Sure sounds good. Should it be automatic or with a parameter?

2021-02-28 13:30 UTC, regevbr commented on lib/expression.js
> +    if (i !== c - 1) {
Sure will do

2021-02-28 13:31 UTC, regevbr commented on lib/expression.js
> +  function stringifyField(arr, min, max) {
I thought about taking all the stringify logic to a separate file and create unit tests just for it but it will just render the tests to be duplicated. I think this is redundant in our case.

2021-02-28 13:33 UTC, regevbr commented on test/ranges_finder.js
> +    var result = findRanges(['L', 'W']);
Indeed the wording might not be to the point but this is what is required of the module. Thoughts about a different name?
Maybe I  should change it to `compact` at it takes an array and compacts it into a "shorter" represnetaion.

2021-02-28 13:35 UTC, regevbr commented on lib/expression.js
> +      if (!value) { // Use default value
No, I actually agree. I will fix

2021-02-28 13:36 UTC, regevbr commented on lib/expression.js
> +      if (!value) { // Use default value
If seconds is ommited? what should we do then?

2021-02-28 13:39 UTC, regevbr commented on lib/parser.js
> +CronParser.stringifyExpression = function stringifyExpression (fields, options) {
how bout stringifyExpressionFields? Maybe we can split the logic for future use:
1. Add a function to create an expression from fields (99% of the current implementation). We can call it `fieldsToExpression`
2. Let the user call the stringify() method on the returned expression.

Thoughts?

2021-02-28 15:07 UTC, regevbr commented on lib/expression.js
> +        if (typeof aliases[match] !== 'undefined') {
This was an error that caused to always return true

2021-02-28 15:09 UTC, regevbr commented on lib/expression.js
> +CronExpression.charConstraints = [
I changed the constrains sturcure to be more readable:
```js
CronExpression.constraints = [
  { min: 0, max: 59, chars: [] }, // Second
  { min: 0, max: 59, chars: [] }, // Minute
  { min: 0, max: 23, chars: [] }, // Hour
  { min: 1, max: 31, chars: ['L'] }, // Day of month
  { min: 1, max: 12, chars: [] }, // Month
  { min: 0, max: 7, chars: [] }, // Day of week
];
```

2021-02-28 15:09 UTC, regevbr commented on test/stringify.js
> +    var expected = '0 * * * * *';
Added optional paramter `includeSeconds` to `stringify()`

2021-02-28 15:10 UTC, regevbr commented on lib/expression.js
> +    if (i !== c - 1) {
Fixed

2021-02-28 15:10 UTC, regevbr commented on test/ranges_finder.js
> +    var result = findRanges(['L', 'W']);
I changed it to `compactField`

2021-02-28 15:11 UTC, regevbr commented on lib/parser.js
> +CronParser.stringifyExpression = function stringifyExpression (fields, options) {
I fixed by applying my last comment here. Usage now is:
```js
var interval = CronParser.fieldsToExpression({
      second: [5,2,1,4,3],
      minute: [1],
      hour: [1],
      month: [1],
      dayOfMonth: [1],
      dayOfWeek: [1],
    });
var expressions = interval.stringify()
```

2021-02-28 15:11 UTC, regevbr commented on lib/expression.js
> +      if (!value) { // Use default value
Fixed

2021-02-28 20:10 UTC, regevbr commented on lib/expression.js
> +  function stringifyField(arr, min, max) {
On 2nd thought you are right. I separated the logic and added ad-hoc unit tests

2021-02-28 21:31 UTC, regevbr commented on test/ranges_finder.js
> +    var result = findRanges(['L', 'W']);
I also improved the algorithm by making it nonrecursive and more readable and added some comments on it

2021-03-01 08:16 UTC, harrisiirak commented on lib/expression.js
> +CronExpression.charConstraints = [
Yep, this works well as a structure.

2021-03-01 08:18 UTC, harrisiirak commented on lib/parser.js
> +CronParser.stringifyExpression = function stringifyExpression (fields, options) {
Yeah, this looks better!

2021-03-01 08:23 UTC, harrisiirak commented on types/index.d.ts
> +import {
> I agree but this is why I took out most of what I could into the common part so it will be shared... In the future, it will be easier to deprecate older ts by just removing the old definition file without trying to use all the new cool features at once. 

Luckily removing/deprecating this TS < 4.1 support is rather easy, therefore let it be at it is.

2021-03-01 08:27 UTC, harrisiirak commented on test/stringify.js
> +    var expected = '0 * * * * *';
`includeSeconds` sounds good. Also as a side note, maybe we also want to add some documentation to this new serialisation functionality. I know, current documentation isn't the best (neither the content or the structure), but it would be probably useful.

2021-03-01 08:28 UTC, regevbr commented on test/stringify.js
> +    var expected = '0 * * * * *';
Sure, will do

2021-03-01 08:35 UTC, regevbr commented on test/stringify.js
> +    var expected = '0 * * * * *';
@harrisiirak I modified the README, please let me know if that works for you

2021-03-01 11:17 UTC, harrisiirak commented
@regevbr Thanks! So far these requested changes looks good, however, I'l have an another round of review ASAP.

2021-03-01 11:25 UTC, regevbr commented
@harrisiirak great! Thanks for investing the time into it :-)

2021-03-03 17:35 UTC, regevbr commented
Hi @harrisiirak sorry to bother you, but did you happen to have another look at the PR?

2021-03-03 18:20 UTC, harrisiirak requested changes
LGTM!

Mostly minor stylistic question but, I think that we can also improve `_handleMaxDaysInMonth` and return value instead of directly mutating the argument.

After these things are solved, it's fit for a release.

2021-03-03 18:20 UTC, harrisiirak commented on lib/expression.js
> +    value = value.replace(/\*/g,constraints.min + '-' + constraints.max);
```suggestion
    value = value.replace(/\*/g, constraints.min + '-' + constraints.max);
```

2021-03-03 18:20 UTC, harrisiirak commented on lib/expression.js
> +CronExpression._handleMaxDaysInMonth = function(mappedFields) {
`mappedFields` as an input is fine, however, maybe it's a bit purer if we don't mutate the input and return the matched value instead and overwrite `dayOfMonth` from the caller context.

2021-03-03 18:20 UTC, harrisiirak commented on lib/expression.js
> +CronExpression.prototype.stringify = function stringify (includeSeconds) {
```suggestion
CronExpression.prototype.stringify = function stringify(includeSeconds) {
```

Space or no space. I can add linter rule later and clean it up as there some mixed patterns in `master` branch too. I myself prefer no extra space here. But yeah,  rather low priority issue.

2021-03-03 18:20 UTC, harrisiirak commented on lib/expression.js
> +  function fieldsToExpression (fields, options) {
No need to wrap it into the function, I think? Inlining it works also well.

2021-03-03 18:20 UTC, harrisiirak commented on lib/field_compactor.js
> +    count: 1,
```suggestion
    count: 1
```

No trailing-comma is used, no enforcement for that tho.

2021-03-03 18:20 UTC, harrisiirak commented on lib/field_compactor.js
> +function compactField(arr) {
Non-recursive version indeed looks better! Good work!

2021-03-03 20:45 UTC, regevbr commented on lib/expression.js
> +    value = value.replace(/\*/g,constraints.min + '-' + constraints.max);
fixed

2021-03-03 20:45 UTC, regevbr commented on lib/expression.js
> +CronExpression._handleMaxDaysInMonth = function(mappedFields) {
fixed

2021-03-03 20:45 UTC, regevbr commented on lib/expression.js
> +CronExpression.prototype.stringify = function stringify (includeSeconds) {
fixed

2021-03-03 20:46 UTC, regevbr commented on lib/expression.js
> +  function fieldsToExpression (fields, options) {
fixed

2021-03-03 20:46 UTC, regevbr commented on lib/field_compactor.js
> +    count: 1,
fixed

2021-03-03 20:46 UTC, regevbr commented on lib/field_compactor.js
> +function compactField(arr) {
:-)

2021-03-03 20:46 UTC, regevbr commented
@harrisiirak CR is much appreciated :-) everything is fixed now

2021-03-04 11:22 UTC, harrisiirak approved these changes

2021-03-04 11:23 UTC, merged

2021-03-04 11:28 UTC, harrisiirak commented
https://github.com/harrisiirak/cron-parser/releases/tag/3.3.0